config/routes.rb
Smokefit::Application.routes.draw do
  root :to => "homepage#show"
  
  # Redirects handled by rails
  match "/contact_us" => redirect('/contact-us')
  
  match "/spages/benefits.htm" => redirect("/benefits")
  match "/spages/how-it-works.htm" => redirect("/how_it_works")
  match "/spages/testimonials.htm" => redirect("/testimonials")
  
  match "site-map/" => redirect("/")
  
  # products urls
  # accesories
  match "/products/accessories/battery.htm" => redirect("/products/electronic-cigarette-battery")
  match "/products/accessories/car-charger.htm" => redirect("/products/car-charger")
  match "/products/accessories/wall-charger.htm" => redirect("/products/wall-charger")
  match "/products/accessories/usb-charger.htm" => redirect("/products/usb-charger")
  match "/products/accessories/plastic-cigarette-box.htm" => redirect("/products/plastic-carrying-case")
  match "/products/accessories/carrying-case-white.htm" => redirect("/products/carrying-case")
  match "/products/accessories/carrying-case-black.htm" => redirect("/products/carrying-case")
  match "/products/accessories/carrying-case-red.htm" => redirect("/products/carrying-case")
  match "/products/accessories/carrying-case-silver.htm" => redirect("/products/carrying-case")
  
  # refills
  match "/products/cartridges/tobacco-strength-8mg.htm" => redirect("/products/tobacco-flavored-refills-high-strength")
  match "/products/cartridges/tobacco-strength-4mg.htm" => redirect("/products/tobacco-flavored-refills-low-strength")
  match "/products/cartridges/menthol-strength-8mg.htm" => redirect("/products/menthol-flavored-refills-high-strength")
  match "/products/cartridges/menthol-strength-4mg.htm" => redirect("/products/menthol-flavored-refills-low-strength")
  match "/products/cartridges/clove-strength-6mg.htm"   => redirect("/products/fruit-flavored-refills")
  match "/products/cartridges/clove-strength-4mg.htm"   => redirect("/products/fruit-flavored-refills")
  
  # products
  match "/products/starter-kits/basic-starter-kit.htm"  => redirect("/products/basic-starter-kit")
  match "/products/starter-kits/deluxe-starter-kit.htm" => redirect("/products/deluxe-kit")
  
  # blog
  match "/blog/" => redirect("http://ezeesmoke.tumblr.com/")
  
  # categories
  match "/products/accessories/"  => redirect("/t/categories/accessories")
  match "/products/refills/"      => redirect("/t/categories/refills")
  match "/products/starter-kits/" => redirect("/t/categories/kits")
  
  match "/spages/terms.htm" => redirect("/terms_of_service")
  
  match "/viewcart/" => redirect("/cart")
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  
  validates :name, :presence => true
  validates :email, :format => {:with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i}
  validates :phone, :presence => true
  
  belongs_to :topic
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/base_controller_decorator.rb
Spree::BaseController.class_eval do
  before_filter :load_root_taxons

  private
  def load_root_taxons
    @taxons ||= Taxonomy.where(:name => "Categories").first.root.children
  end
end

app/controllers/homepage_controller.rb
class HomepageController < Spree::BaseController
  helper :products

  def show
    if params[:page]
      redirect_to(products_path(:page => params[:page]))
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def root_controller?
    unless params[:controller].eql?('homepage') && params[:action].eql?("show")
      return "small-background"
    else
      return ""
    end
  end
end

app/helpers/taxons_helper_decorator.rb
TaxonsHelper.module_eval do
  def breadcrumbs(options={})
    return "" if current_page?("/")

    options.reverse_merge! :taxon => nil, :product => nil, :separator => "&nbsp;&raquo;&nbsp;"

    taxon         = options[:taxon]
    product       = options[:product]
    product_group = options[:product_group]
    separator     = raw(options[:separator])

    crumbs = [content_tag(:li, link_to(t(:home) , root_path) + separator)]

    if taxon
      crumbs << taxon.ancestors.collect { |ancestor| content_tag(:li, link_to(ancestor.name , seo_url(ancestor)) + separator) unless ancestor.root? }.compact unless taxon.ancestors.empty?
    end

    if product
      if taxon
        crumbs << content_tag(:li, link_to(taxon.name, seo_url(taxon)) + separator)
      elsif product_group
        crumbs << content_tag(:li, link_to(product_group.name, pg_search_path(:product_group_name => product_group.permalink)) + separator)
      else
        crumbs << content_tag(:li, link_to("Products", products_url) + separator)
      end
      crumbs << content_tag(:li, content_tag(:span, product.name))
    elsif taxon
      crumbs << content_tag(:li, content_tag(:span, taxon.name))
    elsif product_group
      crumbs << content_tag(:li, content_tag(:span, product_group.name))
    else
      crumbs << content_tag(:li, content_tag(:span, "Products"))
    end
    crumb_list = content_tag(:ul, raw(crumbs.flatten.map{|li| li.mb_chars}.join))
    content_tag(:div, crumb_list, :class => 'breadcrumbs')
  end
end

app/views/checkout/_address.html.erb
<fieldset id='billing'>
  <%= form.fields_for :bill_address do |bill_form| %>
    <legend><%= t("billing_address")%></legend>
    <div class="inner">
      <p class="field">&nbsp;</p>
      <p id="bfname" class="field">
        <%= bill_form.label :firstname, t(:first_name) %>
        <br>
        <%= bill_form.text_field :firstname, :class => 'title' %><span class="req">*</span>
      </p>
      <p id="blname" class="field">
        <%= bill_form.label :lastname, t(:last_name) %>
        <br>
        <%= bill_form.text_field :lastname, :class => 'title' %><span class="req">*</span>
      </p>
      <p id="baddress" class="field">
        <%= bill_form.label :address1, t(:street_address) %>
        <br>
        <%= bill_form.text_field :address1, :class => 'title' %><span class="req">*</span>
      </p>
      <p id="baddress2" class="field">
        <%= bill_form.label :address2, t(:street_address_2) %>
        <br>
        <%= bill_form.text_field :address2, :class => "title" %>
      </p>
      <p id="bcity" class="field">
        <%= bill_form.label :city, t(:city) %>
        <br>
        <%= bill_form.text_field :city, :class => 'title' %><span class="req">*</span>
      </p>
      <% if Spree::Config[:address_requires_state] %>
        <p class="field">
          <span id="bstate">
            <% have_states = !@order.bill_address.country.states.empty? %>
            <%= bill_form.label :state, t(:state) %>
            <br>
            <noscript>
              <%= bill_form.text_field :state_name, :class => 'title' %>
            </noscript>
            <% state_elements = [
               bill_form.collection_select(:state_id, @order.bill_address.country.states,
                                  :id, :name,
                                  {:include_blank => true},
                                  {:class => have_states ? "required" : "hidden",
                                  :disabled => !have_states}) +
                bill_form.text_field(:state_name,
                                  :class => !have_states ? "required" : "hidden",
                                  :disabled => have_states,
                                  :style => "visibility:hidden")
                ].join.gsub('"', "'").gsub("\n", "")
            %>
            <script type="text/javascript" language="javascript" charset="utf-8">
            // <![CDATA[
            document.write("<%= raw state_elements %>");
            // ]]>
            </script>
          </span>
          <span class="req">*</span>
        </p>
      <% end %>
      <p id="bzip" class="field">
        <%= bill_form.label :zipcode, t(:zip) %>
        <br>
        <%= bill_form.text_field :zipcode, :class => 'title' %><span class="req">*</span>
      </p>
      <p id="bcountry" class="field">
        <%= bill_form.label :country_id, t(:country) %>
        <br>
        <span id="bcountry"><%= bill_form.collection_select :country_id, available_countries, :id, :name, {}, {:class => 'title'} %></span>
        <span class="req">*</span>
      </p>
      <p id="bphone" class="field">
        <%= bill_form.label :phone, t(:phone) %>
        <br>
        <%= bill_form.text_field :phone, :class => 'title' %><span class="req">*</span>
      </p>
      <% if Spree::Config[:alternative_billing_phone] %>
        <p id="baltphone">
          <%= bill_form.label :alternative_phone, t(:alternative_phone) %>
          <br>
          <%= bill_form.text_field :alternative_phone %>
        </p>
      <% end %>
    </div>
  <% end %>
</fieldset>


<fieldset id='shipping'>
  <%= form.fields_for :ship_address do |ship_form| %>
    <legend><%= t("shipping_address")%></legend>
    <p class="field checkbox">
      <label for="order_use_billing" id="use_billing">
        <%= check_box_tag 'order[use_billing]', '1', (!(@order.bill_address.empty? && @order.ship_address.empty?) && @order.bill_address.eql?(@order.ship_address)) %> <%= t("use_billing_address") %>
      </label>
    </p>
    <div class="inner">
      <p id="sfname" class="field">
        <%= ship_form.label :firstname, t(:first_name) %>
        <br>
        <%= ship_form.text_field :firstname, :class => 'title' %><span class="req">*</span>
      </p>
      <p id="slname" class="field">
        <%= ship_form.label :lastname, t(:last_name) %>
        <br>
        <%= ship_form.text_field :lastname, :class => 'title' %><span class="req">*</span>
      </p>
      <p id="saddress" class="field">
        <%= ship_form.label :address1, t(:street_address) %>
        <br>
        <%= ship_form.text_field :address1, :class => 'title' %><span class="req">*</span>
      </p>
      <p id="saddress2" class="field">
        <%= ship_form.label :address2, t(:street_address_2) %>
        <br>
        <%= ship_form.text_field :address2, :class => 'title'  %>
      </p>
      <p id="scity" class="field">
        <%= ship_form.label :city, t(:city) %>
        <br>
        <%= ship_form.text_field :city, :class => 'title' %><span class="req">*</span>
      </p>
      <% if Spree::Config[:address_requires_state] %>
        <p class="field">
          <span id="sstate">
            <% have_states = !@order.ship_address.country.states.empty? %>
            <%= ship_form.label :state, t(:state) %>
            <br>
            <noscript>
              <%= ship_form.text_field :state_name, :class => 'required' %>
            </noscript>
            <% state_elements = [
                  ship_form.collection_select(:state_id, @order.bill_address.country.states,
                                    :id, :name,
                                    {:include_blank => false},
                                    {:class => have_states ? "required" : "hidden",
                                    :disabled => !have_states}) +
                  ship_form.text_field(:state_name,
                                    :class => !have_states ? "required" : "hidden",
                                    :disabled => have_states)
                ].join.gsub('"', "'").gsub("\n", "")
            %>
            <script type="text/javascript" language="javascript" charset="utf-8">
            // <![CDATA[
            document.write("<%= raw state_elements %>");
            // ]]>
            </script>
          </span>
          <span class="req">*</span>
        </p>
      <% end %>
      <p id="szip" class="field">
        <%= ship_form.label :zipcode, t(:zip) %>
        <br>
        <%= ship_form.text_field :zipcode, :class => 'title' %><span class="req">*</span>
      </p>
      <p id="scountry" class="field">
        <%= ship_form.label :country_id, t(:country) %>
        <br>
        <span id="scountry"><%= ship_form.collection_select :country_id, available_countries, :id, :name, {}, {:class => 'title'} %></span>
        <span class="req">*</span>
      </p>
      <p id="sphone" class="field">
        <%= ship_form.label :phone, t(:phone) %>
        <br>
        <%= ship_form.text_field :phone, :class => 'title' %><span class="req">*</span>
          </p>
          <% if Spree::Config[:alternative_shipping_phone] %>
            <p id="saltphone">
              <%= ship_form.label :alternative_phone, t(:alternative_phone) %>
              <%= ship_form.text_field :alternative_phone %>
            </p>
          <% end %>
    </div>
  <% end %>
</fieldset>

<hr class="space" />
<div class="form-buttons">
  <input type="submit" class="continue button primary css3button-ligth-blue" value="<%=t("save_and_continue") %>" />
</div>

<div style="display:none">
  <% Country.all.each do  |country| %>
    <div country_id="<%= country.id %>">
      <option value=''></option>
      <% country.states.each do |state| %>
        <option value="<%= state.id %>"><%= state.name %></option>
      <% end %>
    </div>
  <% end %>
</div>


<% content_for :javascripts do %>
  <%= javascript_tag do %>
    $(document).ready(function(){
      if($('#order_use_billing').is(':checked')){
        $('#order_use_billing').next().toggle();
      }
      $('#order_use_billing').bind('click', function(){
        //hides or show the billing address attributes
        $(this).parents('p').next().toggle();
      });
      
      //the code that will change the contents of the state select box
      $("#order_bill_address_attributes_country_id").change(function(){
        $("#order_bill_address_attributes_country_id option:selected").each(function () {
          var selected_id = $(this).attr('value'),
          options = $('div[country_id=' + selected_id + ']').html();
          $('#order_bill_address_attributes_state_id').html(options);
        });
      });
      
    });
  <% end %>
<% end %>

app/views/checkout/_checkout_tab_content.html.erb
<!-- START TAB CONTENT -->
  <% if controller.action_name == 'registration' %>
	  <%= render 'registration' %>
  <% else %>
    <%= form_for @order, :url => update_checkout_path(@order.state) do |form| %>
      <%= render @order.state, :form => form %>
    <% end %>
  <% end %>
<!-- END TAB CONTENT -->

app/views/checkout/_checkout_tabs.html.erb
<div id="tabs" role="tabs">
  <ul>
    <li <%= controller.action_name == "registration" ? "class='active'" : "" %>><span class="number">1</span><span class="title">Create an Account</span></li>
    <li <%= controller.action_name == "edit" && params[:state].eql?("address") ? "class='active'" : "" %>><span class="number">2</span><span class="title">Billing Address</span></li>
    <li <%= controller.action_name == "edit" && params[:state].eql?("delivery") ? "class='active'" : "" %>><span class="number">3</span><span class="title">Shipping Method</span></li>
    <li <%= controller.action_name == "edit" && params[:state].eql?("payment") ? "class='active number'" : "class=number" %>><span class="number">4</span><span class="title">Payment</span></li>
    <li <%= controller.action_name == "edit" && params[:state].eql?("confirm") ? "class='active number'" : "class=number" %>><span class="number">5</span><span class="title">Place Order</span></li>
  </ul>
</div>

app/views/checkout/_delivery.html.erb
<fieldset id='shipping_method'>
  <legend><%= t("shipping_method") %></legend>
  <div class="inner">
    <div id="methods">
      <p class="field radios">
        <% @order.rate_hash.each do |shipping_method| %>
          <label>
            <%= radio_button(:order, :shipping_method_id, shipping_method[:id]) %>
            <%= shipping_method[:name] %> <%= number_to_currency shipping_method[:cost] %>
          </label><br />
        <% end %>
      </p>
    </div>
    <% if Spree::Config[:shipping_instructions] && @order.rate_hash.present? %>
      <p id="minstrs">
        <%= form.label :special_instructions, t("shipping_instructions") %><br />
        <%= form.text_area :special_instructions, :cols => 40, :rows => 7 %>
      </p>
    <% end %>
  </div>
</fieldset>

<div class="form-buttons">
  <input type="submit" class="continue button primary css3button-ligth-blue" value="<%=t("save_and_continue") %>"/>
</div>

app/views/checkout/_registration.html.erb
<%= render 'shared/social_users' %>

<hr>

<%= render 'shared/local_users' %>

app/views/checkout/_summary.html.erb
<div id="aside" role="aside">
  <h3><%= t(:order_summary) %></h3>
  
  <table id="cart-detail">
    <% for line_item in @order.line_items %>
      <% variant = line_item.variant %>
      <tr>
        <td class="qty">(<%= line_item.quantity %>)</td>
        <td class="description"><%= variant.product.name %></td>
        <td class="price"><%= number_to_currency(line_item.price) %></td>
      </tr>
    <% end %>
  </table>
  
  <table class="total">
    <tr>
      <th>Subtotal</th>
      <td><%= number_to_currency @order.item_total %></td>
    </tr>
    <% @order.adjustments.each do |adjustment| %>
      <tr>
        <th><%= adjustment.label %></th>
        <td class="amount"><%= number_to_currency adjustment.amount -%></td>
      </tr>
    <% end %>
    <tr class="totals bold">
      <th>Total</th>
      <td><%= number_to_currency @order.total %></td>
    </tr>
  </table>
</div>

app/views/checkout/edit.html.erb
<div class="span-24 last">
  <div id="title" role="title" class="span-24 last">
    <h1>CHECKOUT</h1>
  </div>
  
  <div class="span-18">
    <%= render "shared/error_messages", :target => @order %>
    <%= render 'checkout_tabs' %>
    <div class="span-18 last">
      <div id="tab-content">
        <%= render 'checkout_tab_content' %>
      </div>
    </div>
  </div>
  <!-- END MAIN CONTENT -->
  
  <div class="span-6 last">
    <%= render 'summary' %>
  </div>
</div>

<hr class="space">

app/views/checkout/payment/_gateway.html.erb
<%= image_tag "creditcard.gif", :id => 'creditcard-image' %>
<% param_prefix = "payment_source[#{payment_method.id}]" %>

<p class="field">
  <label for=""><%= t("card_number") %></label><br />
  <% options_hash = Rails.env.production? ? {:autocomplete => "off"} : {} %>
  <%= text_field_tag "#{param_prefix}[number]", '', options_hash.merge(:id => 'card_number', :class => 'required title', :size => 19, :maxlength => 19) %>
  <span class="req">*</span>
  &nbsp;
  <span id="card_type" style="display:none;">
    ( <span id="looks_like" ><%= t('card_type_is') %> <span id="type"></span></span>
      <span id="unrecognized"><%= t('unrecognized_card_type') %></span>
    )
  </span>
</p>
<p class="field">
  <label for=""><%= t("expiration") %></label><br />
  <%= select_month(Date.today, :prefix => param_prefix, :field_name => 'month', :use_month_numbers => true, :class => 'required') %>
  <%= select_year(Date.today, :prefix => param_prefix, :field_name => 'year', :start_year => Date.today.year, :end_year => Date.today.year + 15, :class => 'required') %>
  <span class="req">*</span>
</p>
<p class="field">
  <label for=""><%= t("card_code") %></label><br />
  <%= text_field_tag "#{param_prefix}[verification_value]", '', options_hash.merge(:id => 'card_code', :class => 'required title', :size => 5) %>
  <span class="req">*</span>
  <a href="/content/cvv" target="_blank" onclick="window.open(this.href,'cvv_info','left=20,top=20,width=500,height=500,toolbar=0,resizable=0,scrollbars=1');return false">
    (<%= t("whats_this") %>)
  </a>
</p>
<%= hidden_field param_prefix, 'first_name', :value => @order.billing_firstname %>
<%= hidden_field param_prefix, 'last_name',  :value => @order.billing_lastname %>

app/views/checkout/registration.html.erb
<div class="span-24 last">
  <div id="title" role="title" class="span-24 last">
    <h2>CHECKOUT</h2>
  </div>
  
  <div class="span-18">
    <%= render 'checkout_tabs' %>
    <div class="span-18 last">
      <div id="tab-content">
        <%= render 'checkout_tab_content' %>
      </div>
    </div>
  </div>
  <!-- END MAIN CONTENT -->
  
  <div class="span-6 last">
    <%= render 'summary' %>
  </div>
</div>

<hr class="space">

app/views/orders/show.html.erb
<% @body_id = 'cart' %>


<div id="content" role="content">
  <h2>Order details</h2>
  
  <p class="actions">
    <%=link_to t('back_to_store'), root_path, :class => 'continue' %> &nbsp;
    or &nbsp;
    <%= link_to t("my_account"), account_path, :class => 'button' %>
  </p>

  <table id="cart-detail">
    <thead>
      <tr>
        <th colspan="2"><%= t("item") %></th>
        <th><%= t("price") %></th>
        <th>&nbsp;</th>
        <th><%= t("qty") %></th>
        <th>&nbsp;</th>
        <th><%= t("total") %></th>
      </tr>
    </thead>
    <tbody id="line_items">
      <% @order.line_items.each do |line_item| %>
        <%- variant = line_item.variant -%>
        <tr class="<%= cycle('', 'alt') %>">
          <td class="image">
            <% if variant.images.length == 0 %>
              <%= small_image(variant.product) %>
            <% else %>
              <%=  image_tag variant.images.first.attachment.url(:small)   %>
            <% end %>
          </td>
          <td class="description">
            <h4><%= link_to variant.product.name,  product_path(variant.product) %></h4>
            <%= variant_options variant %>
          </td>
          <td class="unit-price">
            <%=  product_price(line_item) %>
          </td>
          <td class="operator">
            X
          </td>
          <td class="quantity">
            <%= line_item.quantity %>
          </td>
          <td class="operator">
            =
          </td>
          <td class="total">
            <%= format_price(product_price(line_item, :format_as_currency => false) * line_item.quantity) unless line_item.quantity.nil? %>
          </td>
        </tr>
      <% end %>
      <tr class="totals">
        <td colspan="6">Item Subtotal</td>
        <td class="totals">
          <%= order_price(@order) %>
        </td>
      </tr>
      <% @order.adjustments.each do |adjustment| %>
        <tr class="totals">
          <td colspan="6">
            <%= adjustment.label %>
          </td>
          <td class="totals">
            <%= number_to_currency adjustment.amount %>
          </td>
        </tr>
      <% end %>
      <tr class="totals">
        <td colspan="6">Total</td>
        <td class="totals">
          <%= number_to_currency @order.total %>
        </td>
      </tr>
    </tbody>
  </table>

</div>

app/views/products/_cart_form.html.erb
<%= form_for :order, :url => populate_orders_url do |f| %>
  <%= hook :inside_product_cart_form do %>
  
    <% if product_price(@product) %>
      <%= hidden_field_tag (@product.has_variants? ? :quantity : "variants[#{@product.master.id}]"), 1, :class => "title", :size => 3 %>
      
      <dl class="product-information span-8 last">
        <dt class="span-3">Price</dt>
        <dd class="span-4 last"><span class="bold big"><%= product_price(@product) %></span></dd>
      </dl>
      
      <% if @product.has_variants? %>
        <div id="product-variants">
          <h4><%= "Presentations" %></h4>
          <ul class="product_variants">
            <%  has_checked = false
            @product.variants.active.each_with_index do |v,index|
              next if v.option_values.empty? || (!v.in_stock && !Spree::Config[:show_zero_stock_products])
              checked = !has_checked && (v.in_stock || Spree::Config[:allow_backorders])
              has_checked = true if checked %>
              <li>
                <table>
                  <tr>
                    <td><%= radio_button_tag "products[#{@product.id}]", v.id, checked, :disabled => !v.in_stock && !Spree::Config[:allow_backorders] %></td>
                    <td>
                      <div>
                        <label for="<%= "products_#{@product.id}_#{v.id}" %>">
                          <% if image = v.images.first %>
                            <a href="<%= image.attachment.url(:original) %>" rel="facebox" class="variant">
                              <%= image_tag(image.attachment.url(:mini)) %>
                            </a>
                          <% end %>
                          <div class="variant-description">
                            <%= variant_options v %>
                            <% if variant_price_diff v %>
                              <%= variant_price_diff v %>
                            <% end %>
                          </div>
                          
                        </label>
                      </div>
                    </td>
                  </tr>
                </table>
              </li>
            <% end%>
          </ul>
        </div>

      <% end%>
      
      <!-- <dl class="product-information span-8 last upc">
              <span class="upc-small">
                <dt class="span-3">PART NUMBER</dt>
                <dd class="span-4 last"><%= @product.sku %></dd>
              </span>
            </dl> -->
      
      <!--       <dl class="product-information span-8 last">
              <dt class="span-3">Price</dt>
              <dd class="span-4 last"><span class="bold big"><%= product_price(@product) %></span></dd>
            </dl> -->
      
      <!--       <dl class="product-information span-8 last">
              <dt class="span-3">Shipping</dt>
              <dd class="span-4 last"><span>FREE</span></dd>
            </dl> -->
      
      <dl class="product-information span-8 last">
        <dt class="span-3">In Stock</dt>
        <dd class="span-4 last"><span class="<%= @product.has_stock? ? "green" : "red" %>"><%= @product.has_stock? ? "YES" : "NO" %></span></dd>
      </dl>
      <hr />
  
    <% end %>
  
    <% if @product.cross_sells.present? %>
      <div class="extras">
        <% @product.cross_sells.each do |cross_sell| %>
          <p>
            <%= check_box_tag "variants[#{cross_sell.master.id}]", 1 %>
            <label for="">
              Add <em>'<%= link_to cross_sell.name, product_url(cross_sell) %>'</em> for <%= product_price(cross_sell) %>
            </label>
          </p>
        <% end %>
      </div>
      <hr />
    <% end %>
    
    <% if @product.has_stock? %>
      <button type="submit" class="css3button-ligth-green">Add to cart</button>
    <% end %>
  <% end %>
<% end %>

<% content_for :head do %>
  <%= javascript_include_tag 'product' %>
<% end %>

app/views/products/_image.html.erb
<% image ||= @product.images.first %>
<% if image %>
  <div id="main-image">
    <%= link_to image_tag(image.attachment.url(:product)), image.attachment.url(:original), :rel => "facebox" %>
  </div>
  Click image to enlarge
<% end %>

app/views/products/_taxons.html.erb
<% content_for :sidebar_index_top do %>
  <% if !@product.taxons.blank? %>
    <div class="grey-box">
      <div>
        <h2><%= t('look_for_similar_items') %></h2>
        <%= hook :product_taxons do %>
        <div>
          <ul id='similar_items_by_taxon'>
            <% @product.taxons.each do |taxon| %>
              <li><%= link_to taxon.name, "/t/#{taxon.permalink}" %></li>
            <% end %>
          </ul>
        </div>
        <% end %>
      </div>
    </div>
    <hr class="space">
  <% end %>
<% end %>

app/views/shared/_products.html.erb
<%
  paginated_products = @searcher.products if params.key?(:keywords)
  paginated_products ||= products
%>

<%= will_paginate(paginated_products,
                    :previous_label => "&#171; #{t('previous')}",
                    :next_label => "#{t('next')} &#187;") %>
<hr class="space">

<% if products.empty? %>
  <%= t(:no_products_found) %>
<% elsif params.key?(:keywords) %>
  <h3><%= t(:search_results, :keywords => h(params[:keywords])) %></h3>
<% end %>

<div class="span-24 last">
  <% if products.any? %>
    <% product_count = products.size %>
    <div class="span-15">
      <% products.each_with_index do |product, index| %>
        <% if Spree::Config[:show_zero_stock_products] || product.has_stock? %>
          <div class="product-information">
            <div class="span-7">
              <%= link_to product_image(product, :width => "253px", :height => "147px"), product %>
            </div>
            <div class="span-8 last">
              <h3><%= link_to product.name, product_path(product) %></h3>
              <p><%= truncate strip_tags(product.description), :length => 300 %></p>
              <div class="span-5 price">
                Only <%= product_price(product) %>
              </div>
              <div class="span-3 last">
                <%= link_to 'View More', product_path(product), :class => 'css3button-ligth-blue' %>
              </div>
            </div>
          </div>
          <% if index < product_count - 1 %>
            <hr class="space"><hr class="dashed">
          <% end %>
        <% end %>
      <% end %>
    </div>
  <% end %>
  
  <!-- Sidebar -->

  <%= render :partial => 'shared/product_index_sidebar' %>

  <%= will_paginate(paginated_products,
                      :previous_label => "&#171; #{t('previous')}",
                      :next_label => "#{t('next')} &#187;") %>
  
  <!-- end span-24 last -->
</div>

<% if paginated_products.respond_to?(:total_pages)
      params.delete(:search)
      params.delete(:taxon)
    end
%>